### PR TITLE
Add ATMega4809 from Arduino Nano Every to list as `Doesn't work`

### PR DESCRIPTION
**Pull request by bigjosh**
Does not compile. Possibly the ATMega4809 has different i2c registers? I will try to look into it and send a PR if I get it working.

Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by ladyada** [comment]
whats the error?

**Comment by bigjosh** [comment]
First few pages pasted below. Errors with the new ATMega4809 emulation stuff both on and off.

```
"C:\\Users\\passp\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega4809 -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO_EVERY -DARDUINO_ARCH_MEGAAVR -DMILLIS_USE_TIMERB3 -DNO_EXTERNAL_I2C_PULLUP "-IC:\\Users\\passp\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.5\\cores\\arduino/api/deprecated" "-IC:\\Users\\passp\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.5\\cores\\arduino" "-IC:\\Users\\passp\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.5\\variants\\nona4809" "-IC:\\Users\\passp\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.5\\libraries\\Wire\\src" "-ID:\\Documents\\Arduino\\libraries\\Adafruit_GFX_Library" "-ID:\\Documents\\Arduino\\libraries\\Adafruit_IS31FL3731_Library" "-IC:\\Users\\passp\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.5\\libraries\\SPI\\src" "D:\\Documents\\Arduino\\libraries\\Adafruit_GFX_Library\\Adafruit_SPITFT.cpp" -o "C:\\Users\\passp\\AppData\\Local\\Temp\\arduino_build_105536\\libraries\\Adafruit_GFX_Library\\Adafruit_SPITFT.cpp.o"
In file included from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:36:0:

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:31:19: error: conflicting declaration 'typedef uint8_t PORT_t'

  typedef uint8_t  PORT_t;            ///< PORT values are 8-bit

                   ^~~~~~

In file included from c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:677:0,

                 from c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/String.h:30,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/Print.h:24,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/Stream.h:25,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/Client.h:22,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/Arduino.h:23,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\libraries\SPI\src/SPI.h:23,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:25,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:36:

c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\iom4809.h:1093:3: note: previous declaration as 'typedef struct PORT_struct PORT_t'

 } PORT_t;

   ^~~~~~

In file included from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:36:0:

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h: In member function 'void Adafruit_SPITFT::SPI_CS_HIGH()':

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:282:19: error: no match for 'operator|=' (operand types are 'volatile PORT_t {aka volatile PORT_struct}' and 'PORT_t {aka PORT_struct}')

         *csPort   |= csPinMaskSet;

         ~~~~~~~~~~^~~~~~~~~~~~~~~

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h: In member function 'void Adafruit_SPITFT::SPI_CS_LOW()':

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:304:19: error: no match for 'operator&=' (operand types are 'volatile PORT_t {aka volatile PORT_struct}' and 'PORT_t {aka PORT_struct}')

         *csPort   &= csPinMaskClr;

         ~~~~~~~~~~^~~~~~~~~~~~~~~

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h: In member function 'void Adafruit_SPITFT::SPI_DC_HIGH()':

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:323:19: error: no match for 'operator|=' (operand types are 'volatile PORT_t {aka volatile PORT_struct}' and 'PORT_t {aka PORT_struct}')

         *dcPort   |= dcPinMaskSet;

         ~~~~~~~~~~^~~~~~~~~~~~~~~

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h: In member function 'void Adafruit_SPITFT::SPI_DC_LOW()':

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:342:19: error: no match for 'operator&=' (operand types are 'volatile PORT_t {aka volatile PORT_struct}' and 'PORT_t {aka PORT_struct}')

         *dcPort   &= dcPinMaskClr;

         ~~~~~~~~~~^~~~~~~~~~~~~~~

In file included from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\libraries\SPI\src/SPI.h:23:0,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:25,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:36:

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp: In constructor 'Adafruit_SPITFT::Adafruit_SPITFT(uint16_t, uint16_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':

C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/Arduino.h:123:102: error: no match for 'operator=' (operand types are 'PORT_t {aka PORT_struct}' and 'int')

 #define digitalPinToBitMask(pin) ( (pin < NUM_TOTAL_PINS) ? digital_pin_to_bit_mask[pin] : NOT_A_PIN )

                                                                                                      ^

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:181:26: note: in expansion of macro 'digitalPinToBitMask'

     dcPinMaskSet        =digitalPinToBitMask(dc);

                          ^~~~~~~~~~~~~~~~~~~

In file included from c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:677:0,

                 from c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/String.h:30,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/Print.h:24,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/Stream.h:25,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/Client.h:22,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/Arduino.h:23,

                 from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\libraries\SPI\src/SPI.h:23,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:25,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:36:

c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\iom4809.h:1059:16: note: candidate: PORT_struct& PORT_struct::operator=(const PORT_struct&)

 typedef struct PORT_struct

                ^~~~~~~~~~~

c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\iom4809.h:1059:16: note:   no known conversion for argument 1 from 'int' to 'const PORT_struct&'

c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\iom4809.h:1059:16: note: candidate: PORT_struct& PORT_struct::operator=(PORT_struct&&)

c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\iom4809.h:1059:16: note:   no known conversion for argument 1 from 'int' to 'PORT_struct&&'

In file included from C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\libraries\SPI\src/SPI.h:23:0,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.h:25,

                 from D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:36:

C:\Users\passp\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/Arduino.h:123:102: error: no match for 'operator=' (operand types are 'PORT_t {aka PORT_struct}' and 'int')

 #define digitalPinToBitMask(pin) ( (pin < NUM_TOTAL_PINS) ? digital_pin_to_bit_mask[pin] : NOT_A_PIN )

                                                                                                      ^

D:\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_SPITFT.cpp:183:26: note: in expansion of macro 'digitalPinToBitMask'

     swspi.sckPinMaskSet =digitalPinToBitMask(sck);

                          ^~~~~~~~~~~~~~~~~~~

In file included from c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:677:0,

                 from c:\users\passp\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,
~~~

**Comment by ladyada** [comment]
hiya this looks like errors in adafruit GFX, not this library

**Comment by bigjosh** [comment]
I've noticed that the new stuff that comes in the ATMega4809 core has some breaking changes, maybe this is one of them? I need to get this working on the Every, so happy to put in the time to figure it out.

**Comment by ladyada** [comment]
yes its a totally new chipset and has broken some things - it seems to have been fixed here
https://github.com/adafruit/Adafruit-GFX-Library/pull/235

**Comment by ladyada** [comment]
closing because this doesnt seem to be an issue in this library

**Comment by bigjosh** [comment]
Does not compile cleanly even with latest version of GFX. Problem turned out to be a change in the Wire library on the megaavr code used by the Nano Every. Fixed with this PR...

https://github.com/adafruit/Adafruit_IS31FL3731/pull/11

**Pull request closed without merging**
